version: "3.7"

services: #says what are we gonna orchestrate
    #backend
    smart-brain-api:
        container_name: backend
        #image: node:carbon-jessie
        build: ./ #allows us to build fom our own dokcerfile instead of a default image like node:8.11
        command: npm start
        environment:
            POSTGRES_URI: postgres://sam:tentacles@postgres:5432/smartbrain

        links:
            - postgres #service name
        # depends_on:
        #     - postgres #service name
        working_dir: /usr/src/smart-brain-api
        ports:
            - "3000:3000"
        volumes:
            - ./:/usr/src/smart-brain-api
    #database
    postgres:
        #sometimes u dont need this that is the image name itself
        build: ./postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: sam
            POSTGRES_PASSWORD: tentacles
            #POSTGRES_URL: postgres://sam:tentacles@localhost:5432/smartbrain
            #POSTGRES_URL: postgres://sam:tentacles@db:5432/smartbrain
            POSTGRES_DB: smartbrain
            POSTGRES_HOST: postgres #referenced by the service name and by using links

        # volumes:
        #- ./pgdata:/var/lib/postgresql/data
